# Generated by Django 5.0 on 2025-12-26 00:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseUnit',
            fields=[
                ('unit_id', models.AutoField(primary_key=True, serialize=False)),
                ('unit_name', models.CharField(max_length=100)),
                ('unit_type', models.CharField(choices=[('POLICE', 'Police'), ('FIRE', 'Fire'), ('MEDICAL', 'Medical')], max_length=20)),
                ('current_location', models.CharField(max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('EN_ROUTE', 'En Route'), ('ON_SCENE', 'On Scene'), ('UNAVAILABLE', 'Unavailable')], default='AVAILABLE', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('alert_id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ROUTED', 'Routed'), ('ACTIVE', 'Active'), ('RESOLVED', 'Resolved')], default='PENDING', max_length=20)),
                ('emergency_type', models.CharField(choices=[('POLICE', 'Police'), ('FIRE', 'Fire'), ('MEDICAL', 'Medical')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to=settings.AUTH_USER_MODEL)),
                ('assigned_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='alerts.responseunit')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('CITIZEN', 'Citizen'), ('ADMIN', 'Administrator'), ('RESPONDER', 'Responder')], default='CITIZEN', help_text='User role', max_length=20)),
                ('phone_number', models.CharField(blank=True, help_text='Contact phone number', max_length=20)),
                ('address', models.CharField(blank=True, help_text='Home address', max_length=500)),
                ('city', models.CharField(blank=True, help_text='City', max_length=100)),
                ('assigned_unit', models.ForeignKey(blank=True, help_text='Response unit assigned to this responder', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_responders', to='alerts.responseunit')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
