# Generated by Django 5.0 on 2025-12-16 03:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this emergency report', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the person reporting the emergency', max_length=200)),
                ('contact_info', models.CharField(help_text='Email or phone number for contact', max_length=200)),
                ('emergency_type', models.CharField(choices=[('MEDICAL', 'Medical Emergency'), ('FIRE', 'Fire Emergency'), ('POLICE', 'Police Emergency'), ('OTHER', 'Other Emergency')], help_text='Type of emergency', max_length=20)),
                ('location', models.CharField(help_text='Text description of the location', max_length=500)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Latitude coordinate', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Longitude coordinate', max_digits=9, null=True)),
                ('description', models.TextField(help_text='Detailed description of the emergency')),
                ('status', models.CharField(choices=[('NEW', 'New'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved')], default='NEW', help_text='Current status of the emergency report', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the report was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the report was last updated')),
            ],
            options={
                'verbose_name': 'Emergency Report',
                'verbose_name_plural': 'Emergency Reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
