# Generated by Django 5.0 on 2025-12-16 03:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emergencyreport',
            name='contact_info',
        ),
        migrations.RemoveField(
            model_name='emergencyreport',
            name='name',
        ),
        migrations.AddField(
            model_name='emergencyreport',
            name='reported_by',
            field=models.ForeignKey(default=1, help_text='User who reported the emergency', on_delete=django.db.models.deletion.CASCADE, related_name='emergency_reports', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('CITIZEN', 'Citizen'), ('ADMIN', 'Administrator')], default='CITIZEN', help_text='User role in the system', max_length=20)),
                ('phone_number', models.CharField(help_text='Contact phone number', max_length=20)),
                ('address', models.CharField(help_text='Home address', max_length=500)),
                ('city', models.CharField(help_text='City', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
