# Generated by Django 5.0 on 2025-12-26 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alert',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Alert', 'verbose_name_plural': 'Alerts'},
        ),
        migrations.AlterModelOptions(
            name='responseunit',
            options={'verbose_name': 'Response Unit', 'verbose_name_plural': 'Response Units'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
        migrations.AlterModelTable(
            name='alert',
            table='alerts',
        ),
        migrations.AlterModelTable(
            name='responseunit',
            table='response_units',
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table='user_profiles',
        ),
    ]
