# Generated by Django 5.0 on 2025-12-26 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_alter_alert_options_alter_responseunit_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='assigned_unit',
            field=models.ForeignKey(blank=True, db_column='assigned_unit', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='alerts.responseunit'),
        ),
    ]
