# Generated by Django 5.0 on 2025-12-17 20:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_create_initial_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(help_text='Unique name for the unit (e.g., Police Car 12, Ambulance 5)', max_length=120, unique=True)),
                ('unit_type', models.CharField(choices=[('POLICE', 'Police Unit'), ('FIRE', 'Fire Unit'), ('MEDICAL', 'Medical Unit')], help_text='Type of response unit', max_length=20)),
                ('current_location', models.CharField(help_text='Current location of the unit', max_length=255)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('EN_ROUTE', 'En Route'), ('ON_SITE', 'On Site'), ('UNAVAILABLE', 'Unavailable')], default='AVAILABLE', help_text='Current status of the unit', max_length=20)),
                ('contact_info', models.CharField(blank=True, help_text='Contact information (phone/radio)', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Response Unit',
                'verbose_name_plural': 'Response Units',
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_name', models.CharField(help_text='Name of the zone (e.g., Downtown, North District)', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of the zone')),
                ('coordinates', models.TextField(blank=True, help_text='Geographic coordinates (JSON format for polygon)')),
            ],
            options={
                'verbose_name': 'Zone',
                'verbose_name_plural': 'Zones',
            },
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('CITIZEN', 'Citizen'), ('ADMIN', 'Administrator'), ('RESPONDER', 'Emergency Responder')], default='CITIZEN', help_text='User role in the system', max_length=20),
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emergency_type', models.CharField(choices=[('MEDICAL', 'Medical Emergency'), ('FIRE', 'Fire Emergency'), ('POLICE', 'Police Emergency'), ('OTHER', 'Other Emergency')], help_text='Type of emergency', max_length=20)),
                ('location', models.CharField(help_text='Text description of the location', max_length=500)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Latitude coordinate', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Longitude coordinate', max_digits=9, null=True)),
                ('description', models.TextField(help_text='Detailed description of the emergency')),
                ('status', models.CharField(choices=[('NEW', 'New'), ('DISPATCHED', 'Dispatched'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('CANCELLED', 'Cancelled')], default='NEW', help_text='Current status of the alert', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the alert was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the alert was last updated')),
                ('user', models.ForeignKey(help_text='User who created the alert', on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to=settings.AUTH_USER_MODEL)),
                ('zone', models.ForeignKey(blank=True, help_text='Geographic zone where the alert originated', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='alerts.zone')),
            ],
            options={
                'verbose_name': 'Alert',
                'verbose_name_plural': 'Alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ASSIGNED', 'Assigned'), ('EN_ROUTE', 'En Route'), ('ON_SITE', 'On Site'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='ASSIGNED', help_text='Current status of the response', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Notes about the response')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, help_text='When the unit was assigned')),
                ('arrived_at', models.DateTimeField(blank=True, help_text='When the unit arrived on site', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the response was completed', null=True)),
                ('alert', models.ForeignKey(help_text='Alert this response is addressing', on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='alerts.alert')),
                ('response_unit', models.ForeignKey(help_text='Response unit assigned', on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='alerts.responseunit')),
            ],
            options={
                'verbose_name': 'Response',
                'verbose_name_plural': 'Responses',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='assigned_unit',
            field=models.ForeignKey(blank=True, help_text='Response unit assigned to this responder', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_responders', to='alerts.responseunit'),
        ),
    ]
