# Generated by Django 5.0 on 2025-12-26 00:51

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_alter_alert_assigned_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='timestamp',
            field=models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
        ),
    ]
