# Generated by Django 5.0 on 2025-12-17 20:23

from django.db import migrations


def add_seed_data(apps, schema_editor):
    """Add initial response units to the database."""
    ResponseUnit = apps.get_model('alerts', 'ResponseUnit')
    
    # Police Units
    police_units = [
        {'unit_name': 'Police Car 1', 'unit_type': 'POLICE', 'current_location': 'Downtown Station', 'contact_info': 'Radio: PD-001'},
        {'unit_name': 'Police Car 2', 'unit_type': 'POLICE', 'current_location': 'North Precinct', 'contact_info': 'Radio: PD-002'},
        {'unit_name': 'Police Car 3', 'unit_type': 'POLICE', 'current_location': 'South Precinct', 'contact_info': 'Radio: PD-003'},
    ]
    
    # Fire Units
    fire_units = [
        {'unit_name': 'Fire Truck 1', 'unit_type': 'FIRE', 'current_location': 'Fire Station 1', 'contact_info': 'Radio: FD-001'},
        {'unit_name': 'Fire Truck 2', 'unit_type': 'FIRE', 'current_location': 'Fire Station 2', 'contact_info': 'Radio: FD-002'},
        {'unit_name': 'Ladder 1', 'unit_type': 'FIRE', 'current_location': 'Fire Station 1', 'contact_info': 'Radio: FD-003'},
    ]
    
    # Medical Units
    medical_units = [
        {'unit_name': 'Ambulance 1', 'unit_type': 'MEDICAL', 'current_location': 'Central Hospital', 'contact_info': 'Radio: MED-001'},
        {'unit_name': 'Ambulance 2', 'unit_type': 'MEDICAL', 'current_location': 'East Clinic', 'contact_info': 'Radio: MED-002'},
        {'unit_name': 'Ambulance 3', 'unit_type': 'MEDICAL', 'current_location': 'West Medical Center', 'contact_info': 'Radio: MED-003'},
        {'unit_name': 'Paramedic Unit 1', 'unit_type': 'MEDICAL', 'current_location': 'Downtown', 'contact_info': 'Radio: MED-004'},
    ]
    
    # Create all units
    all_units = police_units + fire_units + medical_units
    for unit_data in all_units:
        ResponseUnit.objects.create(**unit_data)


def remove_seed_data(apps, schema_editor):
    """Remove seed data if rolling back."""
    ResponseUnit = apps.get_model('alerts', 'ResponseUnit')
    # Delete all units created by this migration
    unit_names = [
        'Police Car 1', 'Police Car 2', 'Police Car 3',
        'Fire Truck 1', 'Fire Truck 2', 'Ladder 1',
        'Ambulance 1', 'Ambulance 2', 'Ambulance 3', 'Paramedic Unit 1'
    ]
    ResponseUnit.objects.filter(unit_name__in=unit_names).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0004_responseunit_zone_alter_userprofile_role_alert_and_more'),
    ]

    operations = [
        migrations.RunPython(add_seed_data, remove_seed_data),
    ]
