# Generated by Django 5.0 on 2025-12-27 18:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0005_alter_alert_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='alert_uuid',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
