# Generated by Django

from django.db import migrations
from django.contrib.auth.models import User


def create_responder_users(apps, schema_editor):
    """Create responder user accounts linked to response units."""
    UserProfile = apps.get_model('alerts', 'UserProfile')
    ResponseUnit = apps.get_model('alerts', 'ResponseUnit')
    
    #Get response units by name
    try:
        police_car_1 = ResponseUnit.objects.get(unit_name='Police Car 1')
        police_car_2 = ResponseUnit.objects.get(unit_name='Police Car 2')
        fire_truck_1 = ResponseUnit.objects.get(unit_name='Fire Truck 1')
        ambulance_1 = ResponseUnit.objects.get(unit_name='Ambulance 1')
    except ResponseUnit.DoesNotExist:
        print("Warning: Response units not found, skipping responder creation")
        return
    
    responders_data = [
        ('officer1', 'responder123', 'John', 'Smith', 'officer1@dears.local', '555-0101', '100 Police Plaza', police_car_1),
        ('officer2', 'responder123', 'Sarah', 'Johnson', 'officer2@dears.local', '555-0102', '200 North Precinct', police_car_2),
        ('firefighter1', 'responder123', 'Mike', 'Davis', 'firefighter1@dears.local', '555-0201', '300 Fire Station 1', fire_truck_1),
        ('paramedic1', 'responder123', 'Emily', 'Wilson', 'paramedic1@dears.local', '555-0301', '400 Central Hospital', ambulance_1),
    ]
    
    for username, password, first_name, last_name, email, phone, address, unit in responders_data:
        # Create user if doesn't exist
        if not User.objects.filter(username=username).exists():
            user = User.objects.create_user(
                username=username,
                email=email,
                password=password,
                first_name=first_name,
                last_name=last_name
            )
            
            # Update profile
            profile = user.profile
            profile.role = 'RESPONDER'
            profile.phone_number = phone
            profile.address = address
            profile.city = 'Metropolitan City'
            profile.assigned_unit_id = unit.id  # Use ID instead of object
            profile.save()
            
            print(f"Created responder: {username} -> {unit.unit_name}")


def remove_responder_users(apps, schema_editor):
    """Remove responder users."""
    User = apps.get_model('auth', 'User')
    usernames = ['officer1', 'officer2', 'firefighter1', 'paramedic1']
    User.objects.filter(username__in=usernames).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0005_add_seed_data'),
    ]

    operations = [
        migrations.RunPython(create_responder_users, remove_responder_users),
    ]
