# Generated by Django 5.0 on 2025-12-27 18:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0006_alert_alert_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='alert_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
