# Generated by Django 5.0 on 2025-12-24 18:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0006_create_responder_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='alert',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='id',
        ),
        migrations.AddField(
            model_name='alert',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this alert', primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='response',
            name='alert',
            field=models.ForeignKey(help_text='Alert this response is addressing', on_delete=models.deletion.CASCADE, related_name='responses', to='alerts.alert'),
        ),
    ]
