# Generated by Django 5.0 on 2025-12-28 00:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0007_alter_alert_alert_uuid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Report submission time')),
                ('arrival_time', models.DateTimeField(blank=True, help_text='Time arrived at scene', null=True)),
                ('completion_time', models.DateTimeField(blank=True, help_text='Time incident completed', null=True)),
                ('description', models.TextField(help_text='Description of the incident')),
                ('actions_taken', models.TextField(help_text='Actions taken by responder')),
                ('outcome', models.CharField(choices=[('RESOLVED', 'Resolved'), ('REFERRED', 'Referred to Another Agency'), ('ONGOING', 'Ongoing')], default='RESOLVED', help_text='Outcome of the response', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional notes')),
                ('alert', models.ForeignKey(help_text='Associated alert', on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='alerts.alert')),
                ('responder', models.ForeignKey(help_text='Responder who submitted the report', on_delete=django.db.models.deletion.CASCADE, related_name='submitted_reports', to=settings.AUTH_USER_MODEL)),
                ('response_unit', models.ForeignKey(blank=True, help_text='Response unit involved', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='alerts.responseunit')),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'db_table': 'reports',
                'ordering': ['-timestamp'],
            },
        ),
    ]
