# Generated by Django 5.0 on 2025-12-28 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0008_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='responseunit',
            name='contact_info',
            field=models.CharField(blank=True, help_text='Contact information for the response unit', max_length=100, null=True),
        ),
    ]
